---
- name: Include all tasks
  become: true
  block:
    - name: Include preparation tasks
      ansible.builtin.import_tasks:
        file: prep.yml
    - name: Include package tasks
      ansible.builtin.import_tasks:
        file: package.yml
    - name: Include service tasks
      ansible.builtin.import_tasks:
        file: service.yml
