---
- name: Updating and upgrading packages
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes

- name: Ensure gzip is installed
  ansible.builtin.apt:
    name: gzip
    state: present

- name: Create chisel directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /var/log/chisel/
    - "{{ chisel_config_folder }}"
