---
dependency:
  name: galaxy
  options:
    role-file: molecule/requirements.yml
    requirements-file: molecule/requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    platform: amd64
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  inventory:
    host_vars:
      instance:
        ansible_user: root
verifier:
  name: ansible
