---
- name: Prepare
  hosts: all
  pre_tasks:
    - name: Create .ssh folder in the users home folder (for github actions).
      ansible.builtin.file:
        path: "~/.ssh/"
        mode: '0700'
        state: directory
      delegate_to: localhost

    - name: Ensure needed ssh keypair is created.
      community.crypto.openssh_keypair:
        path: "~/.ssh/id_rsa"
      delegate_to: localhost

    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install OpenSSH.
      ansible.builtin.apt:
        name: openssh-server
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install OpenSSH.
      ansible.builtin.yum:
        name: openssh-server
        update_cache: true
      when: ansible_os_family == "RedHat"

    - name: Install OpenSSH.
      community.general.zypper:
        name: openssh
        update_cache: true
      when: ansible_distribution == "openSUSE Leap"
