---
name: CI
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
      - 'meta/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.editorconfig'
      - '.ansible-lint'
      - '.yamllint'
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'meta/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.editorconfig'
      - '.ansible-lint'
      - '.yamllint'
  schedule:
    - cron: "0 16 * * *"
  release:
    types: [prereleased, released]

jobs:
  test:
    name: Run molecule tests.
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu2204
          - ubuntu2004
          - rockylinux8
          - rockylinux9
          - fedora38

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: |
          pip3 install ansible molecule molecule-plugins[docker] docker yamllint ansible-lint
          ansible-galaxy collection install --force --requirements-file molecule/requirements.yml

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

  release:
    name: Push release to Ansible Galaxy.
    if: github.event_name == 'release'
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
